<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-LSIEJKN" ignored="0" name="test1" tests="6" failures="3" timestamp="2020-11-20T10:47:59 CST" time="0.024" errors="0">
  <testcase name="test1" time="0.0" classname="com.webtest.demo.FreeMarker"/>
  <testcase name="test2" time="0.0" classname="com.webtest.demo.FreeMarker"/>
  <testcase name="test3" time="0.0" classname="com.webtest.demo.FreeMarker">
    <failure type="java.lang.AssertionError" message="expected [1] but found [13]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [13]
at com.webtest.demo.FreeMarker.test3(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.0" classname="com.webtest.demo.FreeMarker"/>
  <testcase name="test5" time="0.0" classname="com.webtest.demo.FreeMarker">
    <failure type="java.lang.AssertionError" message="expected [11] but found [13]">
      <![CDATA[java.lang.AssertionError: expected [11] but found [13]
at com.webtest.demo.FreeMarker.test5(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase name="test6" time="0.0" classname="com.webtest.demo.FreeMarker">
    <failure type="java.lang.AssertionError" message="expected [12] but found [13]">
      <![CDATA[java.lang.AssertionError: expected [12] but found [13]
at com.webtest.demo.FreeMarker.test6(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test6 -->
</testsuite> <!-- test1 -->
